# Railway Nixpacks configuration
[build]
# Python runtime
providers = ["python"]

[variables]
# Django settings
DJANGO_SETTINGS_MODULE = "portfolio_blog.settings_railway"
PYTHONPATH = "/app"

[start]
# Start command
cmd = "gunicorn portfolio_blog.wsgi:application --bind 0.0.0.0:$PORT"